version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.8-browsers
    steps:
      - checkout
      - run: yarn install
      - run: npx jest
workflows:
  version: 2
  commit:
    jobs:
      - test
  scheduled:
    triggers:
      - schedule:
          cron: "0,10,20,30,40,50 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test